language: ruby
cache:
  bundler: true
  npm: true
  yarn: true
#bundler_args: --full-index
rvm:
  - 2.5.3
services:
  - postgresql
before_install:
  - gem update --system
  - gem install bundler:2.1.4
before_script:
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn install
  - psql -c 'create database makerspacerepo_test;' -U postgres
  - mkdir certs && touch certs/saml.key && touch certs/saml.crt
  - openssl req -x509 -newkey rsa:4096 -keyout certs/saml.key -out certs/saml.crt -days 1 -nodes -subj "/C=CA/ST=Ontario/L=Ottawa/O=uOttawa/OU=Richard L'Abbé Makerspace/CN=makerepo.com/emailAddress=travis-ci@makerepo.com"
jobs:
  include:
    - stage: test
      name: Test
      script:
        - bundle exec rails db:environment:set RAILS_ENV=test
        - bundle exec rails db:migrate RAILS_ENV=test
        - bundle exec rails spec RAILS_ENV=test
        - bundle exec rails test RAILS_ENV=test
    - stage: deploy
      name: Deploy
      script:
        - openssl aes-256-cbc -k $DEPLOY_KEY -d -a -in config/deploy_id_rsa_enc_travis -out config/deploy_id_rsa
        - chmod 600 config/deploy_id_rsa
        - eval "$(ssh-agent -s)"
        - ssh-add config/deploy_id_rsa
        - gem install capistrano
        - bundle exec cap staging deploy
stages:
  - name: test
  - name: deploy
    if: branch = staging
notifications:
  slack:
    rooms:
      - secure: oHDfEWV0mSjs0EVsbQAs9Dcbzz+/ylHGV/D/6mT1+R1otaa6w88gqPdXyciyZsEfJDIDUaj7fhhmpr9Q+91ISVo0BXvenbxOmjK0HNs7qKiemFHT2UhgiE59JIMXdZo8VXcW2eWazbBfwlcf4zSeJqb7jg02rRZdbE0FERuzvQ7M/cnqGEid1YHy7kmjfKR0IwRH96YWdcVxmeroT6B9YZaziUjsTrQanAjfmpAZ0r2C04mPx1CYEo6lg/rFRZAdGo4nTjQ2kaNZW4PFRDWX4sksFaYzJZinlb3mublY9XtI+VqvlJxl96vS2S0NsYPYk9qoXm5XmqEWPefoUdvCTqkkGrDtMDGZdxMjiY9+fryvmnkLWlx+Mcs7IPuSyU2tIctc1pnRIgxsyCygpyiO/VmAyBu/NQSuqYoqxNIis+12Ft48AOHHGfGf8gwVfubAS0e90ih2CxvlJeI5bBGAq2LOJY/bb7hvqCB3PlgZc9hcX02k6zGAnCS8fKPdWQ+K6hM2zrLlCZpwtul78ygQ8GlJry4S2rwosMJIVZQBtsLDIGesyqnHTWig+ppYFYrzy85y+iykg1dA6UJWmnhrKhm1hc8ORWJh39plGqHzbto5n+eSSEK/ylQoNAmTXcbyJZrYq+kdEUHhcFSnW4LWVWBdndkS2/AvxgiRp0aQnkk=
    on_success: change
    on_failure: always
    on_error: always
env:
  secure: V+aW4dcaqX0gdv8lIlya1YtnYvrgNfsPw9vj3EhTD57pwjCQrXqsD3AcGTYPUtyd46Lhj6jwc2n6+JYLB2AyCi43VFYCIY1Bc2rIdAgQKaTYz/n9XbIpV9CQi2uuezx7ejHFUGPtXXMO6wYU5U4CxTYkX1f6XU5DT/0GTDX4124wI8p9WGETOYUon/JkCi4yEZXh4BY6n7yfbugWiBE+R3bFPgQRVjSb/xd4A3Axwkw7JBRGbqio43VflTI3oGVcfj6H1K5VBGrqgcGetFzr2vlcpR5CERCgmomcHHW0fHGaEqG+vj/55K5pieI4SBBZ98xh+2b6a+vfqNRg9YM3SxnWLAD0iyEMeqQ4EP2MxxVfBe6t6VetTTN8F/+y9V8aykG1ZdtWObqJHL2DZl0HMKy18f+A3dKMKG/gwGqt50hJKur/EjoKkk4fi3p/+/jLKMgalOEl0pUKHEXXNJ3rxJLVv781jxo1/OnHTIz/9N7KQe0Ms21QuUU4MQoXOZIh/0fU1nfBDqg8xF8z5tpBsb/EbVkc7zND2pVST0eN5zsO26Whpxx6r6wPDuhua/d6GG2WTsiQsZmgTbxGOSKGTJQIpInwok0Y/G53xZ7+nONStQFABtZRLpqeAC4we1ThYHZtBmWP86Asl8vJwyfkCObeAFAXPjAQlFBZm7IhPzw=
