default: &default
  adapter: <%= Rails.application.credentials[Rails.env.to_sym][:database][:adapter] || postgresql %>
  host: <%= Rails.application.credentials[Rails.env.to_sym][:database][:host] || localhost %>
  port: <%= Rails.application.credentials[Rails.env.to_sym][:database][:port] || 5432 %>
  username: <%= Rails.application.credentials[Rails.env.to_sym][:database][:username] || postgres %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:database][:password] || postgres %>

development:
  <<: *default
  database: <%= Rails.application.credentials[Rails.env.to_sym][:database][:name] || makerspacerepo %>

test:
  <<: *default
  database: <%= "#{Rails.application.credentials[Rails.env.to_sym][:database][:name]}#{ENV['TEST_ENV_NUMBER']}" || 'makerspacerepo_test' %>

production:
  <<: *default
  database: <%= Rails.application.credentials[Rails.env.to_sym][:database][:name] %>

staging:
  <<: *default
  database: <%= Rails.application.credentials[Rails.env.to_sym][:database][:name] %>
