default: &default
  adapter: postgresql
  host: <%= ENV["DB_HOST"] || "localhost" %>
  port: <%= ENV["DB_PORT"] || 5432 %>
  username: <%= ENV["DB_USERNAME"] || "postgres" %>
  password: <%= ENV["DB_PASSWORD"] || "postgres" %>

development:
  <<: *default
  database: <%= ENV["DB_NAME"] || "makerspacerepo" %>

test:
  <<: *default
  database: makerspacerepo_test

production:
  <<: *default
  database: <%= ENV["DB_NAME"] || "makerspacerepo" %>
