# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_region: <%= ENV["S3_REGION"] %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  acclaim_api: <%= ENV['ACCLAIM_API'] %>
  sidekiq_username: <%= ENV['SIDEKIQ_USERNAME'] %>
  sidekiq_password: <%= ENV['SIDEKIQ_PASSWORD'] %>
  shopify_shop_name: <%= ENV['SHOPIFY_SHOP_NAME'] %>
  shopify_api_key: <%= ENV['SHOPIFY_API_KEY'] %>
  shopify_shared_secret: <%= ENV['SHOPIFY_SHARED_SECRET'] %>
  shopify_api_version: 2020-04
  shopify_password: <%= ENV['SHOPIFY_PASSWORD'] %>
  shopify_webhook: <%= ENV['SHOPIFY_WEBHOOK'] %>

test:
  secret_key_base: f686aef6bfafa1346ab160de62c54375f2ebf90fd5b7ef9cb8974bde9c36c6d146f3e84ef426d1757a054c5e17349db5215fa1d74253681e503365231a39b2ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_user: <%= ENV["SMTP_USER"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  s3_region: s3-us-west-2
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"] %>
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  github_app_key: <%= ENV['GITHUB_APP_KEY'] %>
  github_app_key_secret: <%= ENV['GITHUB_APP_KEY_SECRET'] %>
  acclaim_api: <%= ENV['ACCLAIM_API'] %>
  shopify_shop_name: <%= ENV['SHOPIFY_SHOP_NAME'] %>
  shopify_api_key: <%= ENV['SHOPIFY_API_KEY'] %>
  shopify_shared_secret: <%= ENV['SHOPIFY_SHARED_SECRET'] %>
  shopify_api_version: 2020-04
  shopify_password: <%= ENV['SHOPIFY_PASSWORD'] %>
  shopify_webhook: <%= ENV['SHOPIFY_WEBHOOK'] %>
