name: Deploy Dev
on: [push]

env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  deploy:
    if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Setup certs
        env:
          DEPLOY_ENC_KEY: ${{ secrets.DEPLOY_ENC_KEY }}
        run: |
          mkdir certs && touch certs/saml.key && touch certs/saml.crt
          openssl req -x509 -newkey rsa:4096 -keyout certs/saml.key -out certs/saml.crt -days 1 -nodes -subj "/C=CA/ST=Ontario/L=Ottawa/O=uOttawa/OU=Richard L'Abbé Makerspace/CN=makerepo.com/emailAddress=travis-ci@makerepo.com"
          openssl enc -d -aes-256-cbc -md sha512 -salt -in config/deploy_id_rsa_enc -out config/deploy_id_rsa -k $DEPLOY_ENC_KEY -a -pbkdf2
          chmod 600 config/deploy_id_rsa
          eval "$(ssh-agent -s)"
          ssh-add config/deploy_id_rsa
          gem install capistrano
          BRANCH=${{ steps.extract_branch.outputs.branch }} bundle exec cap dev_server deploy
